// src/react/components/BusinessService.jsx
/* eslint-disable react/jsx-no-target-blank */
import React from 'react';

export default function Example() {
  return (
    <div className="space-y-2">
      <div className="example">
        <h1>Positive Grid 徵資深前端工程師</h1>
        <a
          target="_blank"
          href="https://www.cakeresume.com/companies/positive-grid/jobs/96bc55"
          className="btn"
        >點我</a>
      </div>
      <div className="example">
        <h1>React 全攻略入門班 - 假日班</h1>
        <h4>報名加碼送價值千元「Webpack 5 入門 線上課程」!</h4>
        <img src="https://5xruby.tw/assets/images/talks/cover/react-js-c77f3549.jpg" alt="" className="mw-100" />
        <a
          target="_blank"
          href="https://5xruby.tw/talks/react-js/?utm_source=milkmidi-react-vue"
          className="btn mt-2"
        >點我</a>
      </div>
    </div>
  );
}

// src/vue/components/BusinessService.vue
<script>
export default {
  setup() {
    return {
    };
  },
};
</script>

<template>
  <div class="space-y-2">
    <div class="example">
      <h1>Vue.js 與 Vuex 前端開發實戰課程</h1>
      <img class="mw-100" src="https://5xruby.tw/assets/images/talks/cover/vue-js-61eaa1c7.jpg" alt="">
      <a
        target="_blank"
        href="https://5xruby.tw/talks/vue-js/?utm_source=milkmidi-react-vue"
        class="btn mt-2"
      >點我</a>
    </div>
  </div>
</template>
