// src/react/components/Example4_conditional_rendering.jsx
import React, { useState } from 'react';

export default function Example4() {
  const [show, setShow] = useState(true);
  const atClick = () => {
    setShow(!show);
  };
  return (
    <div className="example">
      <button className="btn mb-1" onClick={atClick}>switch show:{show.toString()}</button>
      {
        show && (
          <h1 className="border p-3 bg-react text-white rounded">React</h1>
        )
      }
      <h2
        style={{
          display: show ? 'block' : 'none'
        }}
        className="border p-3 bg-react text-white rounded"
      >css display block/none</h2>
    </div>
  );
}

// src/vue/components/Example4_conditional_rendering.vue
<script>

export default {
  data() {
    return {
      show: true
    };
  },
};
</script>

<template>
  <div class="example">
    <button class="btn mb-1" @click="show=!show">switch show:{{ show }}</button>
    <h1 v-if="show" class="border p-3 bg-vue text-white rounded">Vue</h1>
    <h2 v-show="show" class="border p-3 bg-vue text-white rounded">css display block/none</h2>
  </div>
</template>
