// src/react/components/Example0_state.jsx
import React, { useState } from 'react'

export default function Example() {
  const [count, setCount] = useState(0);
  const atClick = () => {
    setCount(count + 1);
  }
  return (
    <section data-name="Example0_state">
      <h1>{count}</h1>
      <button
        className="btn btn-primary"
        onClick={atClick}>addCount</button>
    </section>
  )
};

// src/vue/components/Example0_state.vue
<script>
export default {
  data() {
    return {
      count: 0
    }
  },
  methods: {
    atClick(){
      this.count += 1;
    }
  },
};
</script>

<template>
  <section data-name="Example0_state">
    <h1>{{count}}</h1>
    <button class="btn btn-primary" @click="atClick">addCount</button>
  </section>
</template>
