// src/vue/components/Example2_ref.vue
<script>
import { ref } from 'vue';

export default {
  setup() {
    // composition 無法使用 this
    const domRef = ref();
    const atClick = () => {
      domRef.value.focus();
    };
    return {
      domRef,
      atClick
    };
  },
  methods: {
    atClick2() {
      // 或是直接使用 this.$refs 取得
      this.$refs.domRef.focus();
    }
  }
};
</script>

<template>
  <div class="example">
    <input ref="domRef" class="form-control">
    <button class="btn" @click="atClick">focusInput</button>
    <button class="btn" @click="atClick2">focusInput</button>
  </div>
</template>

// src/react/components/Example2_ref.jsx
import React, { useRef } from 'react';

export default function Example2() {
  const domRef = useRef();
  const atClick = () => {
    domRef.current.focus();
  };
  return (
    <div className="example">
      <input className="form-control" ref={domRef} type="text" />
      <button className="btn" onClick={atClick}>focusInput</button>
    </div>
  );
}
