// src/vue/components/Example5_lists.vue
<script>

export default {
  data() {
    return {
      lists: ['vue', 'React', 'angular', 'jQuery']
    };
  },
};
</script>

<template>
  <div class="example">
    <ul class="border">
      <li v-for="text in lists" :key="text">{{ text }}</li>
    </ul>

    <ul class="border">
      <template v-for="text in lists" :key="text">
        <li>{{ text }}</li>
        <hr>
      </template>
    </ul>
  </div>
</template>

// src/react/components/Example5_lists.jsx
import React, { useState } from 'react';

export default function Example5() {
  const [lists] = useState(['React', 'vue', 'angular', 'jQuery']);

  return (
    <div className="example">
      <ul className="border">
        { lists.map((text) => <li key={text}>{text}</li>) }
      </ul>
      <ul className="border">
        {
          lists.map((text) => (
            <React.Fragment key={text}>
              <li>{text}</li>
              <hr />
            </React.Fragment>
          ))
        }
      </ul>
    </div>
  );
}
