// src/vue/components/Example3_lifecycle.vue
<script>
import { onMounted, onUnmounted } from 'vue';

export default {
  setup() {
    onMounted(() => {
      console.log('vue composition onMounted');
    });
    onUnmounted(() => {
      console.log('vue composition onUnmounted');
    });
  },
  mounted() {
    // dom 已更新，所以 this.$refs.root 有值
    console.log('vue mounted');
    console.log(this.$refs.root);
  },
  unmounted() {
    // dom 已更新，所以 this.$refs.root 會是 null
    console.log('vue unmounted');
    console.log(this.$refs.root);
  }
};
</script>

<template>
  <div class="example">
    <div class="border p-3 bg-vue text-white rounded">
      <h1 ref="root">Vue, lifecycle</h1>
    </div>
  </div>
</template>

// src/react/components/Example3_lifecycle.jsx
import React, { useRef, useEffect } from 'react';

export default function Example2() {
  const domRef = useRef();
  useEffect(() => {
    console.log('React Component Mounted');
    // useEffect 會等到 render 完成後才發生
    // 此時可以存取元素
    console.log(domRef.current);
    return () => {
      console.log('React Component Unmount');
      // React 17.x 更新了 useEffect clear 時間點
      // useEffect clear 會等到 render 完成後才發生
      // 此時元素已刪除，所以 dom 會是 null
      console.log(domRef.current); // this is null
    };
  }, []); // 這裡要填空 Array
  return (
    <div className="example">
      <div className="border p-3 bg-react text-white rounded">
        <h1 ref={domRef}>React, lifecycle</h1>
      </div>
    </div>
  );
}
