// src/vue/App.vue
<script>
import {
  onMounted, onBeforeUnmount, ref
} from 'vue';
import PrismCode from './components/PrismCode';
import * as Syntax from './components/.syntax';

import Example0 from './components/Example0_state.vue';
import Example0Composition from './components/Example0_state_composition.vue';
import Example1 from './components/Example1_props.vue';
import Example2 from './components/Example2_ref.vue';
import Example3 from './components/Example3_lifecycle.vue';

export default {
  components: {
    PrismCode,
    Example0,
    Example0Composition,
    Example1,
    Example2,
    Example3,
  },
  setup() {
    const exampleIdx = ref(window.currentIndex || 0);
    const show = ref(true);

    const handler = ({ detail }) => {
      exampleIdx.value = detail;
    };
    onMounted(() => {
      window.addEventListener('changeExample', handler);
    });
    onBeforeUnmount(() => {
      window.removeEventListener('changeExample', handler);
    });

    return {
      exampleIdx,
      Syntax,
      show,
    };
  },
};
</script>

<template>
  <div class="vue-app">
    <div class="text-center">
      <img class="logo" src="../assets/vue.png">
    </div>
    <section v-if="exampleIdx === 0">
      <h6>
        <p>使用 data, 並回傳 Object</p>
        <p>要更新值就直接寫 this.xxx = 新值, vue 會自動重新 render</p>
        <p>template 偵聽函式可以直接寫參數 atClick(5)</p>
      </h6>
      <Example0 />
      <PrismCode :code="Syntax.Example0_state" />
    </section>

    <section v-if="exampleIdx === 0" data-name="Composition API">
      <h6>
        <p>Vue3 新的 Composition API</p>
        <p>使用 ref 或 reactive 來宣告變數</p>
      </h6>
      <Example0Composition />
      <PrismCode :code="Syntax.Example0_state_composition" />
    </section>

    <section v-if="exampleIdx === 1">
      <h6>
        <p>props 一定要定義，不然 vue 會讀不到</p>
        <p>如果傳了該 Component 未定義的 props, 會放到 html 的 attributes</p>
      </h6>
      <Example1 name="milkmidi" :count="9527" />
      <PrismCode :code="Syntax.Example1_props" />
    </section>

    <section v-if="exampleIdx === 2">
      <h6>
        <p>Vue 使用 ref, 或是 this.$refs</p>
      </h6>
      <hr>
      <Example2 />
      <PrismCode :code="Syntax.Example2_ref" />
    </section>

    <section v-if="exampleIdx === 3">
      <h6>
        <p>mounted, unmounted</p>
      </h6>
      <div class="switch">
        <input v-model="show" type="checkbox">
        <span />
      </div>

      <hr>
      <Example3 v-if="show" />
      <PrismCode :code="Syntax.Example3_lifecycle" />
    </section>
  </div>
</template>

<style>
</style>

// src/react/App.jsx
/* eslint-disable jsx-a11y/alt-text */
import React, { useState } from 'react';
import logo from '../assets/react-logo.svg';
import PrismCode from './components/PrismCode';
import * as Syntax from './components/.syntax';

import Example0 from './components/Example0_state';
import Example1 from './components/Example1_props';
import Example2 from './components/Example2_ref';
import Example3 from './components/Example3_lifecycle';

function App() {
  const [exampleIdx, setExampleIdx] = useState(window.currentIndex || 0);
  const [show, setShow] = useState(true);
  React.useEffect(() => {
    const handler = ({ detail }) => {
      setExampleIdx(detail);
    };
    window.addEventListener('changeExample', handler);
    return () => {
      window.removeEventListener('changeExample', handler);
    };
  }, []);

  return (
    <div className="react-app">
      <div className="text-center">
        <img src={logo} className="logo" />
      </div>
      {
        exampleIdx === 0 && (
          <section>
            <h6>
              <p>React 使用 useState 來宣告，會回傳 Array</p>
              <p>const [count, setCount] = useState(0);</p>
              <p>更新值需使用 setCount(新的值), 直接寫 count = 100; 並不會重新 render</p>
            </h6>
            <hr />
            <Example0 />
            <PrismCode code={Syntax.Example0_state} />
          </section>
        )
      }
      {
        exampleIdx === 1 && (
          <section>
            <h6>
              <p>父組件傳什麼，都會放到 props 裡</p>
              <p>props 型別可以用 PropTypes 定義<br /> 或是flowjs/typescipe定義</p>
            </h6>
            <hr />
            <Example1 name="milkmidi" data-value="9527" />
            <PrismCode code={Syntax.Example1_props} />
          </section>
        )
      }
      {
        exampleIdx === 2 && (
          <section>
            <h6>React 使用 useRef</h6>
            <hr />
            {
              show && <Example2 />
            }
            <PrismCode code={Syntax.Example2_ref} />
          </section>
        )
      }
      {
        exampleIdx === 3 && (
          <section>
            <h6>React 使用 useEffect</h6>
            <div className="switch">
              <input
                type="checkbox"
                checked={show}
                onChange={({ target }) => setShow(target.checked)}
              />
              <span />
            </div>
            <hr />
            {
              show && <Example3 />
            }
            <PrismCode code={Syntax.Example3_lifecycle} />
          </section>
        )
      }
    </div>
  );
}

export default App;
